### ISSUE TITLE
MOZ_ENABLE_WAYLAND=1 not working in .bashrc

### ISSUE THREAD

**Issue by vlad196** [ventureoo/nvidia-tweaks#4]
You have this parameter working in .bashrc or .zshrc?
I noticed that it didn't work when I installed firefox and it was on x11, when it was as if this option wasn't enabled in wayland mode.

I think maybe it has something to do with running the environment to use graphics mode and reading point files.

In this regard, I think it might be better to register the following in the /etc/environment file before bashrc, or better separately for the Wayland session in ~/.configuration/wednesday.d/envvars.conf file, as they write here: [Environment_variables#Per_Wayland_session](https://wiki.archlinux.org/title/Environment_variables#Per_Wayland_session) ?

For example:
`mkdir ~/.config/environment.d/`
```
cat << _EOF_ >> ~/.config/environment.d/envvars.conf
# Wayland environment
SDL_VIDEODRIVER=wayland # Can break some native games
XDG_SESSION_TYPE=wayland
QT_QPA_PLATFORM="wayland;xcb"
MOZ_ENABLE_WAYLAND=1
GBM_BACKEND=nvidia-drm
WLR_NO_HARDWARE_CURSORS=1 
KITTY_ENABLE_WAYLAND=1
_EOF_
```
(export  is not needed)

**Comment by ventureoo** [comment]
Hi. Sorry for the long response.

Indeed, some variables are not always convenient to export to specific shell files. I think the way to specify them in `/etc/environment` is the best, since it works for most cases.

The method you specified through `~/.config/environment.d/` may work like any other, but it depends:
a) on systemd
b) which display manager the user uses, because it only works with GDM (as mentioned in the article).

So yes, we should probably use `/etc/environment`, since this file is currently read by most shells (even non-POSIX compliant ones like fish)
